# Generated by Django 3.2.3 on 2021-05-24 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auto.activity')),
            ],
            bases=('auto.activity',),
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auto.activity')),
            ],
            bases=('auto.activity',),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.make')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometre'), ('mi', 'Mile')], default='km', max_length=2)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PartService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auto.service')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='auto.activity')),
            ],
            bases=('auto.service',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='auto.car')),
                ('parttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.parttype')),
                ('inspection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.inspection')),
                ('replacement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.replacement')),
            ],
        ),
        migrations.CreateModel(
            name='FuelService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auto.service')),
                ('volume', models.PositiveSmallIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuellings', to='auto.car')),
            ],
            bases=('auto.service',),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('name', 'make'), name='makemodel'),
        ),
    ]
