# Generated by Django 3.2.3 on 2021-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model', 'year']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make']},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['parttype']},
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='carmodel',
            name='makemodel',
        ),
        migrations.AddField(
            model_name='car',
            name='myname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
