# Generated by Django 3.2.3 on 2021-05-24 16:39

import datetime
from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='odometer',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='Vehicle Identification Number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
