# Generated by Django 3.2.3 on 2021-05-24 17:10

from django.db import migrations
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20210524_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelservice',
            name='volume',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True),
        ),
    ]
