# Generated by Django 3.2.3 on 2021-07-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20210729_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='myname',
            new_name='name',
        ),
    ]
