# Generated by Django 3.2.3 on 2021-05-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_fuelservice_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.inspection'),
        ),
        migrations.AlterField(
            model_name='part',
            name='replacement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.replacement'),
        ),
    ]
