# Generated by Django 3.2.3 on 2021-05-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20210524_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='part',
            name='replacement',
        ),
        migrations.AddField(
            model_name='activity',
            name='part',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto.part'),
            preserve_default=False,
        ),
    ]
