# Generated by Django 3.2.3 on 2021-05-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20210524_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartService',
            new_name='InspectService',
        ),
        migrations.AlterField(
            model_name='inspectservice',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='auto.inspection'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReplaceService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auto.service')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='auto.replacement')),
            ],
            bases=('auto.service',),
        ),
    ]
