version: "2.4"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    secrets:
      - django_key
    environment:
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOST=localhost
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

secrets:
  django_key:
    file: examplekey
