version: "2.4"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    secrets:
      - django_key
    environment:
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOST=localhost
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"

secrets:
  django_key:
    file: ./examplesecrets/key
